<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="M2B-L-F28PH9R" failures="1" tests="5" name="HomeLoan" time="0.133" errors="0" timestamp="2022-09-02T17:25:02 IST">
  <testcase classname="test.TestNGBasics" name="method1" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.TestNGBasics.method1(TestNGBasics.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="test.TestNGBasics" name="method2" time="0.004"/>
  <testcase classname="test.test4" name="webLoginHomeLoan" time="0.014"/>
  <testcase classname="test.test4" name="webLoginHomeLoan" time="0.005"/>
  <testcase classname="test.test4" name="webLoginHomeLoan" time="0.004"/>
  <testcase classname="test.test4" name="mobileLoginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- mobileLoginHomeLoan -->
  <testcase classname="test.test2" name="method1" time="0.0">
    <ignored/>
  </testcase> <!-- method1 -->
  <testcase classname="test.test4" name="apiLoginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- apiLoginHomeLoan -->
</testsuite> <!-- HomeLoan -->
